# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
