# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_issue_assignmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attend_survey',
            field=models.BooleanField(default=False),
        ),
    ]
