# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_attend_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='difficulty_level',
        ),
    ]
