# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_assignment_difficulty_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoreTypeTracker',
            new_name='AssignmentTypeScoreTracker',
        ),
        migrations.RenameModel(
            old_name='StreakTracker',
            new_name='UserStreakTracker',
        ),
        migrations.RemoveField(
            model_name='skilltypelevel',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='skilltypelevel',
            name='user',
        ),
        migrations.DeleteModel(
            name='SkillTypeLevel',
        ),
    ]
