# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161114_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 16, 31, 48, 996442, tzinfo=utc)),
        ),
    ]
