# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20161115_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('knowledge_from', models.CharField(choices=[('PEN', 'Pensumlitteratur'), ('ØVI', 'Øvinger'), ('EGN', 'Programmering utenom øvinger'), ('E-L', 'Tjenester som Codecademy og Project Euler')], max_length=3)),
                ('knowledge_level', models.CharField(choices=[(0, 'Ubesvart'), (1, 'I svært liten grad'), (2, 'I liten grad'), (3, 'I noen grad'), (4, 'I grad'), (5, 'I svært stor grad')], default=0, max_length=1)),
                ('relevance', models.CharField(choices=[(0, 'Ubesvart'), (1, 'I svært liten grad'), (2, 'I liten grad'), (3, 'I noen grad'), (4, 'I grad'), (5, 'I svært stor grad')], default=0, max_length=1)),
                ('comments', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
    ]
