# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_progresssurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresssurvey',
            name='knowledge_from',
            field=models.CharField(choices=[('PEN', 'Pensumlitteratur'), ('ØVI', 'Øvinger'), ('EGN', 'Programmering utenom øvinger'), ('E-L', 'Tjenester som Codecademy og Project Euler'), ('ANN', 'Annet')], max_length=3),
        ),
        migrations.AlterField(
            model_name='progresssurvey',
            name='knowledge_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ubesvart'), (1, 'I svært liten grad'), (2, 'I liten grad'), (3, 'I noen grad'), (4, 'I grad'), (5, 'I svært stor grad')], default=0),
        ),
        migrations.AlterField(
            model_name='progresssurvey',
            name='relevance',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ubesvart'), (1, 'I svært liten grad'), (2, 'I liten grad'), (3, 'I noen grad'), (4, 'I grad'), (5, 'I svært stor grad')], default=0),
        ),
    ]
