# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20161116_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresssurvey',
            name='motivation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ubesvart'), (1, 'I svært liten grad'), (2, 'I liten grad'), (3, 'I noen grad'), (4, 'I stor grad'), (5, 'I svært stor grad')], default=0),
        ),
        migrations.AlterField(
            model_name='progresssurvey',
            name='knowledge_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ubesvart'), (1, 'I svært liten grad'), (2, 'I liten grad'), (3, 'I noen grad'), (4, 'I stor grad'), (5, 'I svært stor grad')], default=0),
        ),
        migrations.AlterField(
            model_name='progresssurvey',
            name='relevance',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ubesvart'), (1, 'I svært liten grad'), (2, 'I liten grad'), (3, 'I noen grad'), (4, 'I stor grad'), (5, 'I svært stor grad')], default=0),
        ),
    ]
