# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170125_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_type',
        ),
    ]
