# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_assignment_assignment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmenttype',
            options={'verbose_name': 'Assignment Type', 'verbose_name_plural': 'Assignment Types'},
        ),
        migrations.AlterModelOptions(
            name='progresssurvey',
            options={'ordering': ['-answered_at'], 'verbose_name': 'Progress Survey', 'verbose_name_plural': 'Progress Surveys'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
